extracted_headers= [
    "",
    "start",
    "end",
    "today",
    "username",
    "simserial",
    "subscriberid",
    "deviceid",
    "phonenumber",
    "General Questions/Municipality and Ward Details/Name of Municipality (नगरपालिकाको नाम)",
    "General Questions/Municipality and Ward Details/Ward Number (वडा नं .)",
    "General Questions/Municipality and Ward Details/Ward Number (वडा नं )",
    "General Questions/Name of the Tole (सर्वेक्षण भैरहेको स्थानको नाम)",
    "General Questions/House No. (घर नं)",
    "GPS Coordinates",
    "General Questions/_GPS Coordinates_latitude",
    "General Questions/_GPS Coordinates_longitude",
    "General Questions/_GPS Coordinates_altitude",
    "General Questions/_GPS Coordinates_precision",
    "General Questions/Do I have your consent to conduct this survey? (के यो सर्भे गर्नमा तपाइको सहमति छ?)",
    "Basic Details of House Owner/Information on house owner/Name of the house owner (घरमुलीको नाम)",
    "Basic Details of House Owner/Information on house owner/Age of the house owner (घरमुलीको उमेर)",
    "Basic Details of House Owner/Information on house owner/Marital status of house owner (घरमुलीको वैवाहिक स्थिति)",
    "Basic Details of House Owner/Information on house owner/Gender of house owner (घरमुलीको बिवरण)",
    "Basic Details of House Owner/Information on house owner/Is the house owner differently abled? के घर मालिक फरक रूपमा सक्षम हुनहुन्छ?",
    "Basic Details of House Owner/Language and Ethnicity/Mother Tongue (मातृभाषा)",
    "Basic Details of House Owner/Language and Ethnicity/If other, specify here. (यदि अन्य मातृभाषा भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Basic Details of House Owner/Language and Ethnicity/What is the ethnicity of the family? (परिवार कुन जातिमा पर्नुहुन्छ?)",
    "Basic Details of House Owner/Language and Ethnicity/If other, please specify (यदि अन्य भए, यहाँ उल्लेख गर्नुहोस्)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 0 to 4 years. ( ० देखि ४ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 5 to 9 years. ( ५ देखि ९ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 10 to 14 years. ( १० देखि १४ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 15 to 19 years. ( १५ देखि १९ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 20 to 24 years. ( २० देखि २४ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 25 to 29 years. ( २५ देखि २९ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 30 to 34 years. ( ३० देखि ३४ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 35 to 39 years. ( ३५ देखि ३९ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 40 to 44 years. ( ४० देखि ४४ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 45 to 49 years. ( ४५ देखि ४९ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 50 to 54 years. ( ५० देखि ५४ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 55 to 59 years. ( ५५ देखि ५९ वर्षको उमेर समूहमा पर्ने महिला सद",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 60 to 64 years. ( ६० देखि ६४ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 65 to 69 years. ( ६५ देखि ६९ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age group 70 to 74 years. ( ७०  देखि ७४ वर्षको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age group- Female/No. of female members of the age 75+ years. ( ७५ वर्ष भन्दा माथिको उमेर समूहमा पर्ने महिला सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/total_female",
    "Family Members Details/Total Number of Family Members and Age Group Details/Total Number of Female is ${total_female}",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 0 to 4 years. ( ० देखि ४ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 5 to 9 years. ( ५ देखि ९ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 10 to 14 years. ( १० देखि १४ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 15 to 19 years. ( १५ देखि १९ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 20 to 24 years. ( २० देखि २४ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 25 to 29 years. ( २५ देखि २९ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 30 to 34 years. ( ३० देखि ३४ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 35 to 39 years. ( ३५ देखि ३९ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 40 to 44 years. ( ४० देखि ४४ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 45 to 49 years. ( ४५ देखि ४९ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 50 to 54 years. ( ५० देखि ५४ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 55 to 59 years. ( ५५ देखि ५९ वर्षको उमेर समूहमा पर्ने पुरुष  सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 60 to 64 years. ( ६० देखि ६४ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 65 to 69 years. ( ६५ देखि ६९ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age group 70 to 74 years. ( ७०  देखि ७४ वर्षको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/No. of male members of the age 75+ years. ( ७५ वर्ष भन्दा माथिको उमेर समूहमा पर्ने पुरुष सदस्यहरुको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Male/total_male",
    "Family Members Details/Total Number of Family Members and Age Group Details/Total Number of Male is ${total_male}",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 0 to 4 years. ( ० देखि ४ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या )",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 5 to 9 years. ( ५ देखि ९ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 10 to 14 years. ( १० देखि १४ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या) )",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 15 to 19 years. ( १५ देखि १९ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 20 to 24 years. ( २० देखि २४ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 25 to 29 years. ( २५ देखि २९ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 30 to 34 years. ( ३० देखि ३४ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 35 to 39 years. ( ३५ देखि ३९ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 40 to 44 years. ( ४० देखि ४४ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 45 to 49 years. ( ४५ देखि ४९ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 50 to 54 years. ( ५० देखि ५४ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 55 to 59 years. ( ५५ देखि ५९ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 60 to 64 years. ( ६० देखि ६४ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 65 to 69 years. ( ६५ देखि ६९ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age group 70 to 74 years. ( ७०  देखि ७४ वर्षको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/Age Group- Others/No. of other gender members of the age 75+ years. ( ७५ वर्ष भन्दा माथिको उमेर समूहमा पर्ने महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यको संख्या)",
    "Family Members Details/Total Number of Family Members and Age Group Details/total_other",
    "Family Members Details/Total Number of Family Members and Age Group Details/Total Number of Others is ${total_other}",
    "Family Members Details/Total Number of Family Members and Age Group Details/total_members",
    "Family Members Details/Total Number of Family Members and Age Group Details/Total Number of family members is ${total_members}",
    "Family Members Details/Identity Revealing Document/Do the house members have identity revealing documents? (के तपाइँ र तपाईको घरका सदस्यहरुसंग आफ्नो परिचय खुल्ने कागजात छ?)",
    "Family Members Details/Identity Revealing Document/If few members do not have, specify the number. (यदि कसैको छैन भने, कति जनाको छैन यहाँ उल्लेख गर्नुहोस)",
    "Family Members Details/Sensitive Population in the house/Do any of your family member fall under following sensitive population? (के तपाईको घरका सदस्य निम्न लिखित सवेदनशील जनसंख्यामा पर्नुहुन्छ?)/Pregnant and Lactating (गर्भवती तथा स्तनपान गराउने)",
    "Family Members Details/Sensitive Population in the house/Do any of your family member fall under following sensitive population? (के तपाईको घरका सदस्य निम्न लिखित सवेदनशील जनसंख्यामा पर्नुहुन्छ?)/Widowed (विदुवा/विदुर)",
    "Family Members Details/Sensitive Population in the house/Do any of your family member fall under following sensitive population? (के तपाईको घरका सदस्य निम्न लिखित सवेदनशील जनसंख्यामा पर्नुहुन्छ?)/Chronically ill (दिर्घकालिन रोग भएको)",
    "Family Members Details/Sensitive Population in the house/Do any of your family member fall under following sensitive population? (के तपाईको घरका सदस्य निम्न लिखित सवेदनशील जनसंख्यामा पर्नुहुन्छ?)/People with Disability (शारिरिक तथा मानसिक अपांगता भएको)",
    "Family Members Details/Sensitive Population in the house/Do any of your family member fall under following sensitive population? (के तपाईको घरका सदस्य निम्न लिखित सवेदनशील जनसंख्यामा पर्नुहुन्छ?)/Single Woman (एकल महिला)",
    "Family Members Details/Sensitive Population in the house/Do any of your family member fall under following sensitive population? (के तपाईको घरका सदस्य निम्न लिखित सवेदनशील जनसंख्यामा पर्नुहुन्छ?)/None of the above (माथिका कुनै पनि छैन)",
    "Family Members Details/Sensitive Population in the house/Pregnant and Lactating/If pregnant and lactating, specify the number. (यदि गर्भवती र स्तनपान गराउने हुनुहुन्छ भने, कति जना हुनुहुन्छ?",
    "Family Members Details/Sensitive Population in the house/Pregnant and Lactating/If pregnant and lactating, are they differently abled? (यदि गर्भवती तथा स्तनपान गराउने भए, उहाहरु अपाङ्गता भएको वा फरक रुपमा सक्षम हुनुहुन्छ?)",
    "Family Members Details/Sensitive Population in the house/Pregnant and Lactating/If yes, please write down the number of people with disability pregnant and lactating woman (यदि हुनुन्छ भने, अपाङ्गता भएको वा फरक रुपमा सक्षम कति जना हुनुन्छ?",
    "Family Members Details/Sensitive Population in the house/Widowed/If widowed, specify the gender of widowed members (यदि विदुवा/विदुर हुनुन्छ भने, उहाँहरु तल मध्ये कुन हो?)/Female (महिला)",
    "Family Members Details/Sensitive Population in the house/Widowed/If widowed, specify the gender of widowed members (यदि विदुवा/विदुर हुनुन्छ भने, उहाँहरु तल मध्ये कुन हो?)/Male (पुरुष)",
    "Family Members Details/Sensitive Population in the house/Widowed/If widowed, specify the gender of widowed members (यदि विदुवा/विदुर हुनुन्छ भने, उहाँहरु तल मध्ये कुन हो?)/Other (अन्य)",
    "Family Members Details/Sensitive Population in the house/Widowed/How many members in the family members are widowed? (घरका कतिजना सदस्य विधवा/विदुर हुनुहुन्छ?)",
    "Family Members Details/Sensitive Population in the house/Single woman/If single woman, how many members in the family are single woman? (यदि एकल महिला भएमा, कतिजना सदस्य एकल महिलामा पर्नुहुन्छ?)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If differently abled, specify the gender of the differently abled family members (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, उहाँहरु तलका मध्ये कुनमा पर्नुहुन्छ?)/Female (महिला)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If differently abled, specify the gender of the differently abled family members (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, उहाँहरु तलका मध्ये कुनमा पर्नुहुन्छ?)/Male (पुरुष)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If differently abled, specify the gender of the differently abled family members (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, उहाँहरु तलका मध्ये कुनमा पर्नुहुन्छ?)/Other (अन्य)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If people with disability, how many members in the family are people with disability? (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, घरमा कतिजना फरक रुपमा सक्षम हुनुहुन्छ?)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If people with disability, specify the type of disability (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, यी मध्ये कुनमा पर्नुहुन्छ?)/Physical disabilities (शारीरिक असक्षमता)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If people with disability, specify the type of disability (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, यी मध्ये कुनमा पर्नुहुन्छ?)/Visual disabilities (दृष्टि असक्षमता)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If people with disability, specify the type of disability (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, यी मध्ये कुनमा पर्नुहुन्छ?)/Hearing disabilities (श्रवण असक्षमता)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If people with disability, specify the type of disability (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, यी मध्ये कुनमा पर्नुहुन्छ?)/Hearing-Visual disabilities (श्रवण-दृश्य असक्षमता)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If people with disability, specify the type of disability (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, यी मध्ये कुनमा पर्नुहुन्छ?)/Speaking disabilities (बोल्ने असक्षमता)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If people with disability, specify the type of disability (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, यी मध्ये कुनमा पर्नुहुन्छ?)/Mental disabilities (मानसिक असक्षमता)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If people with disability, specify the type of disability (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, यी मध्ये कुनमा पर्नुहुन्छ?)/Intellectual disabilities (बौद्दिक  असक्षमता)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/If people with disability, specify the type of disability (यदि शारिरिक तथा मानसिक अपांगता हुनुहुन्छ भने, यी मध्ये कुनमा पर्नुहुन्छ?)/Multiple disabilities (धेरै असक्षमताहरु)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/Do the people with disability family member have identity revealing document provided by municipality? (के शारिरिक तथा मानसिक अपांगता भएको परिचय पत्र पालिका बाट प्राप्त गर्नुभएको छ?)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/Which type of card have the people with disability member taken? (शारिरिक तथा मानसिक अपांगता व्यक्तिले कुन रंगको कार्ड प्राप्त गर्नुभएको छ?)/Red Card (रातो कार्ड)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/Which type of card have the people with disability member taken? (शारिरिक तथा मानसिक अपांगता व्यक्तिले कुन रंगको कार्ड प्राप्त गर्नुभएको छ?)/Blue Card (निलो कार्ड)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/Which type of card have the people with disability member taken? (शारिरिक तथा मानसिक अपांगता व्यक्तिले कुन रंगको कार्ड प्राप्त गर्नुभएको छ?)/Yellow Card (पहेलो कार्ड)",
    "Family Members Details/Sensitive Population in the house/Differently Abled/Which type of card have the people with disability member taken? (शारिरिक तथा मानसिक अपांगता व्यक्तिले कुन रंगको कार्ड प्राप्त गर्नुभएको छ?)/White Card (सेतो कार्ड)",
    "Family Members Details/Sensitive Population in the house/Chronically ill/If chronically ill, specify gender of chronically ill family members (यदि दिर्घकालिन रोग भएमा, यी मध्ये कुनमा पर्नुहुन्छ?)/Female (महिला)",
    "Family Members Details/Sensitive Population in the house/Chronically ill/If chronically ill, specify gender of chronically ill family members (यदि दिर्घकालिन रोग भएमा, यी मध्ये कुनमा पर्नुहुन्छ?)/Male (पुरुष)",
    "Family Members Details/Sensitive Population in the house/Chronically ill/If chronically ill, specify gender of chronically ill family members (यदि दिर्घकालिन रोग भएमा, यी मध्ये कुनमा पर्नुहुन्छ?)/Other (अन्य)",
    "Family Members Details/Sensitive Population in the house/Chronically ill/If chronically ill, how many members in the family are chronically ill? (यदि दिर्घकालिन रोग भएमा, घरका कतिजना सदस्यहरुलाइ दिर्घकालिन रोग छ?)",
    "Family Members Details/Education Status/Literacy/Total literate female members in the house ( घरमा कुल साक्षर महिला सदस्यहरू)",
    "Family Members Details/Education Status/Literacy/Total literate male members in the house ( घरमा कुल साक्षर पुरुष सदस्यहरू)",
    "Family Members Details/Education Status/Literacy/Total literate other gender members in the house ( घरमा कुल साक्षर महिला वा पुरुष भनि पहिचान नगर्ने  सदस्यहरू)",
    "Family Members Details/Education Status/Literacy/total_literate",
    "Family Members Details/Education Status/Literacy/Total literate members of age between (15-60) years in the house (घरमा (१५-६०) वर्ष उमेर समुहका कुल साक्षर सदस्यहरू)",
    "Family Members Details/Education Status/Total Number of Literate Family Members is ${total_literate}",
    "Family Members Details/Education Status/total_illiterate",
    "Family Members Details/Education Status/Total Number of Illiterate Family Members is ${total_illiterate}",
    "Family Members Details/Education Status/Education Level/Total family members who are not eligible for schooling  (परिवारका कुल सदस्यहरू जो पढ्न योग्य नभएका)",
    "Family Members Details/Education Status/Education Level/Total family members with other/non-formal education (अन्य/अनौपचारिक शिक्षा लिएका परिवारका कुल सदस्यहरू)",
    "Family Members Details/Education Status/Education Level/Total family members whose education level is not known ( कुल परिवारका सदस्य जसको शिक्षा स्तर थाहा छैन)",
    "Family Members Details/Education Status/Education Level/Total family members at primary level of schooling (कक्षा ५ सम्म) विद्यालयको प्राथमिक तहमा (पढ्ने/पढेका  कुल परिवारका सदस्यहरू)",
    "Family Members Details/Education Status/Education Level/Total family members at Lower Secondary level of schooling (विद्यालयको निम्न माध्यमिक तहमा  (कक्षा ८ सम्म) पढ्ने/पढेका  कुल परिवारका सदस्यहरू)",
    "Family Members Details/Education Status/Education Level/Total family members at Secondary level of schooling (विद्यालयको  माध्यमिक तहमा ((कक्षा ९ वा १० सम्म) पढ्ने/पढेका  कुल परिवारका सदस्यहरू)",
    "Family Members Details/Education Status/Education Level/Total family members at SLC or Equivalent level of schooling (SLC वा सो सरह स्तरमा पढ्ने/पढेका परिवारका कुल सदस्यहरू)",
    "Family Members Details/Education Status/Education Level/Total family members at Intermediate or Equivalent level of schooling (+२ पढ्ने/पढेका परिवारका कुल सदस्यहरू)",
    "Family Members Details/Education Status/Education Level/Total family members at Bachelor or Equivalent level of schooling (ब्याचलर वा सो सरह पढेका/पढ्ने परिवारका कुल सदस्यहरू)",
    "Family Members Details/Education Status/Education Level/Total family members at Masters / Ph.D level of education (मास्टर्स/पी.एच.डी पढ्ने/पढेका परिवारका कुल सदस्यहरू)",
    "Other Family Members Details/Are there any other families living in the same house? (तपाईको घरमा अन्य कुनै परिवार बस्नुहुन्छ?)",
    "Other Family Members Details/If yes, how many female members are there? (यदि बस्नुहुन्छ भने, महिला सदस्य कतिजना हुनुहुन्छ?)",
    "Other Family Members Details/How many male members are there? (यदि बस्नुहुन्छ भने, पुरुष सदस्य कतिजना हुनुहुन्छ?)",
    "Other Family Members Details/How many members of other gender are there ? (यदि बस्नुहुन्छ भने, अन्य महिला वा पुरुष भनि पहिचान नगर्ने सदस्य कतिजना हुनुहुन्छ?)",
    "Economic Condition of the House Owner Family/Major Occupation/What is the primary occupation of your family? (तपाईको घरको प्रमुख पेशा कुन हो?)",
    "Economic Condition of the House Owner Family/Major Occupation/If other, please specify (यदि अन्य मुख्य पेशा भए, यहाँ उल्लेख गर्नुहोस्)",
    "Economic Condition of the House Owner Family/Supporting Occupation/What is the secondary Occupation of your family? (तपाइको घरको सहायक पेशा के हो?)/Agriculture and Livestock (कृषि तथा पशुपालन)",
    "Economic Condition of the House Owner Family/Supporting Occupation/What is the secondary Occupation of your family? (तपाइको घरको सहायक पेशा के हो?)/On-farm Daily Wage Worker (कृषि क्षेत्रमा दैनिक ज्याला मजदुर)",
    "Economic Condition of the House Owner Family/Supporting Occupation/What is the secondary Occupation of your family? (तपाइको घरको सहायक पेशा के हो?)/Off-farm Daily Wage Worker (गैर कृषि क्षेत्रमा दैनिक ज्याला मजदुर)",
    "Economic Condition of the House Owner Family/Supporting Occupation/What is the secondary Occupation of your family? (तपाइको घरको सहायक पेशा के हो?)/Business (व्यापार तथा व्यवसाय)",
    "Economic Condition of the House Owner Family/Supporting Occupation/What is the secondary Occupation of your family? (तपाइको घरको सहायक पेशा के हो?)/Government Service (सरकारी सेवा)",
    "Economic Condition of the House Owner Family/Supporting Occupation/What is the secondary Occupation of your family? (तपाइको घरको सहायक पेशा के हो?)/Private Job (निजी सेवा)",
    "Economic Condition of the House Owner Family/Supporting Occupation/What is the secondary Occupation of your family? (तपाइको घरको सहायक पेशा के हो?)/Foreign Employment/Remittance (वैदेशिक रोजगार)",
    "Economic Condition of the House Owner Family/Supporting Occupation/What is the secondary Occupation of your family? (तपाइको घरको सहायक पेशा के हो?)/Other (अन्य)",
    "Economic Condition of the House Owner Family/Supporting Occupation/What is the secondary Occupation of your family? (तपाइको घरको सहायक पेशा के हो?)/No supporting occupation (कुनै सहायक पेशा छैन)",
    "Economic Condition of the House Owner Family/Supporting Occupation/If other, please specify (यदि अन्य सहायक पेशा भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Economic Condition of the House Owner Family/Supporting Occupation/Number of unemployed members in the household (घरमा कतिजना वेरोजगार हुनुहुन्छ?)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/Do you or your family members own land? (के तपाइँ र तपाइको परिवारको नाममा जग्गा-जमिन छ?)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/How much land do you or your family hold? (तपाइँ र तपाईको परिवारको जग्गा कति छ?)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/Please choose the unit of measurement of land area. (कृपया जमिनको क्षेत्रफल नाप्ने इकाइ छनोट गर्नुहोस्)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/If other type, please specify the type of land (यदि अन्य भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/Land Use Type (भू-उपयोगको स्तिथि)/Built-up Area/Land (संरचना भएको क्षेत्र/जमिन)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/Land Use Type (भू-उपयोगको स्तिथि)/Cultivation Area/Land (खेति गरेको क्षेत्र/जमिन)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/Land Use Type (भू-उपयोगको स्तिथि)/Forested Area (वन क्षेत्र)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/Land Use Type (भू-उपयोगको स्तिथि)/Open Space (खुल्ला स्थान)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/Land Use Type (भू-उपयोगको स्तिथि)/Commercial Purpose (व्यापारिक क्षेत्र)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/Land Use Type (भू-उपयोगको स्तिथि)/Unused/Barren Land (प्रयोग नभएको अथवा बाँझो जमिन)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/Land Use Type (भू-उपयोगको स्तिथि)/Other (अन्य)",
    "Economic Condition of the House Owner Family/Land Holding/Land holding details of the family members/If other land type, please specify the type of land (यदि अन्य प्रयोग भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/Do the female members of the house own the land? (घरको महिला सदस्यको नाममा जग्गा-जमिन छ?)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/Total land held by female of the house (घरको महिला सदस्यको नाममा भएको जग्गा कति छ?)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/Please choose the unit of measurement of land area. (कृपया जमिनको क्षेत्रफल नाप्ने इकाइ छनोट गर्नुहोस्)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/If other land type that helds by female, please specify the type of land (महिला सदस्यले यदि अन्य प्रयोग भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/Type of land holding by female (घरको महिला सदस्यको नाममा भएको जग्गा तलउल्लेख मध्ये कुन-कुन मा पर्दछ?)/Built-up Area/Land (संरचना भएको क्षेत्र/जमिन)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/Type of land holding by female (घरको महिला सदस्यको नाममा भएको जग्गा तलउल्लेख मध्ये कुन-कुन मा पर्दछ?)/Cultivation Area/Land (खेति गरेको क्षेत्र/जमिन)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/Type of land holding by female (घरको महिला सदस्यको नाममा भएको जग्गा तलउल्लेख मध्ये कुन-कुन मा पर्दछ?)/Forested Area (वन क्षेत्र)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/Type of land holding by female (घरको महिला सदस्यको नाममा भएको जग्गा तलउल्लेख मध्ये कुन-कुन मा पर्दछ?)/Open Space (खुल्ला स्थान)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/Type of land holding by female (घरको महिला सदस्यको नाममा भएको जग्गा तलउल्लेख मध्ये कुन-कुन मा पर्दछ?)/Commercial Purpose (व्यापारिक क्षेत्र)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/Type of land holding by female (घरको महिला सदस्यको नाममा भएको जग्गा तलउल्लेख मध्ये कुन-कुन मा पर्दछ?)/Unused/Barren Land (प्रयोग नभएको अथवा बाँझो जमिन)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/Type of land holding by female (घरको महिला सदस्यको नाममा भएको जग्गा तलउल्लेख मध्ये कुन-कुन मा पर्दछ?)/Other (अन्य)",
    "Economic Condition of the House Owner Family/Land Holding/Land Holding by female members/If other land type, specify here. (यदि अन्य भू-उपयोग भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Economic Condition of the House Owner Family/Income and Expenditure/Annual income of the family (वार्षिक आम्दानी)",
    "Economic Condition of the House Owner Family/Income and Expenditure/Monthly Expenditure of the house  (घरको मासिक खर्च)",
    "Economic Condition of the House Owner Family/Income and Expenditure/Yearly saving of the house  (घरको वार्षिक बचत)",
    "Economic Condition of the House Owner Family/Saving, Credit and Loan/Have you taken loan from the financial institutions? (के तपाइले कुनै वित्तीय संस्था बाट ऋण लिनुभएको छ?)",
    "Economic Condition of the House Owner Family/Saving, Credit and Loan/Covered by subsidized loan targeted for women/marginalized group (घरको  महिला/सीमान्तकृत समूहका लागि लक्षित सहुलियतपूर्ण ऋण पाएको छ?)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/Is any family member receiving reservations, allowances and special privilege systems? (के तपाइको घरको कुनै सदस्यले कुनै आरक्षण, भत्ता तथा विशेष सुविधाहरु पाउनुभएको छ?)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/If yes, what type of Reservations, allowances and special privilege systems are being received? (यदि छ भने, निम्न मध्ये कुन आरक्षण, भत्ता तथा विशेष सुविधाहरु पाउनुभएको छ?)/Senior Citizen (ज्येष्ठ नागरिक)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/If yes, what type of Reservations, allowances and special privilege systems are being received? (यदि छ भने, निम्न मध्ये कुन आरक्षण, भत्ता तथा विशेष सुविधाहरु पाउनुभएको छ?)/Senior Citizen Dalit (ज्येष्ठ नागरिक दलित)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/If yes, what type of Reservations, allowances and special privilege systems are being received? (यदि छ भने, निम्न मध्ये कुन आरक्षण, भत्ता तथा विशेष सुविधाहरु पाउनुभएको छ?)/Senior Citizen Single Women (ज्येष्ठ नागरिक एकल महिला)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/If yes, what type of Reservations, allowances and special privilege systems are being received? (यदि छ भने, निम्न मध्ये कुन आरक्षण, भत्ता तथा विशेष सुविधाहरु पाउनुभएको छ?)/Widowed (विधवा/ एकल महिला)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/If yes, what type of Reservations, allowances and special privilege systems are being received? (यदि छ भने, निम्न मध्ये कुन आरक्षण, भत्ता तथा विशेष सुविधाहरु पाउनुभएको छ?)/People with Disability (शारिरिक तथा मानसिक अपांगता भएको)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/If yes, what type of Reservations, allowances and special privilege systems are being received? (यदि छ भने, निम्न मध्ये कुन आरक्षण, भत्ता तथा विशेष सुविधाहरु पाउनुभएको छ?)/Dalit Child Allowance (दलित बाल बालिका)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/If yes, what type of Reservations, allowances and special privilege systems are being received? (यदि छ भने, निम्न मध्ये कुन आरक्षण, भत्ता तथा विशेष सुविधाहरु पाउनुभएको छ?)/Pension (पेन्सन)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/If yes, what type of Reservations, allowances and special privilege systems are being received? (यदि छ भने, निम्न मध्ये कुन आरक्षण, भत्ता तथा विशेष सुविधाहरु पाउनुभएको छ?)/Others (अन्य)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/If other type of privilege system, please specify (यदि अन्य किसिमको सुविधाहरु भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/Number of family members receiving elderly citizen allowance (वृद्द भत्ता पाउनुहुने घरका सदस्य)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/Number of family members receiving elderly citizen dalit allowance (दलित वृद्द भत्ता पाउनुहुने घरका सदस्य)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/Number of family members receiving elderly citizen single woman allowance (महिला वृद्द भत्ता पाउनुहुने घरका सदस्य)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/Number of family members receiving  widowed allowance (विधवा भत्ता पाउनुहुने घरका सदस्य)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/Number of family members receiving  allowance for differently abled (अपाङ्गता भत्ता पाउनुहुने घरका सदस्य)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/Number of family members receiving  allowance for dalit child (दलित बाल-बालिका  भत्ता पाउनुहुने घरका सदस्य)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/Number of family members receiving pension (पेन्सन पाउनुहुने घरका सदस्य)",
    "Economic Condition of the House Owner Family/Reservations, Allowances and Special Privilege System/Number of family members receiving other type of allowance (अन्य किसिमका भत्ता पाउनुहुने घरका सदस्य)",
    "Economic Condition of the House Owner Family/Insurance Details/Have you or your family member taken any type of insurance? (के तपाइ तथा तपाँईको परिवारको कुनै सदस्यहरूले विमा गर्नुभएको छ?)",
    "Economic Condition of the House Owner Family/Insurance Details/If yes, what type of insurance have you or your family members taken? (यदि छ भने, तथा तपाँईको परिवारको कुनै सदस्यहरूले निम्न उल्लेख मध्ये कुन कुन विमा गर्नुभएको छ?)/Life Insurance (जीवन विमा)",
    "Economic Condition of the House Owner Family/Insurance Details/If yes, what type of insurance have you or your family members taken? (यदि छ भने, तथा तपाँईको परिवारको कुनै सदस्यहरूले निम्न उल्लेख मध्ये कुन कुन विमा गर्नुभएको छ?)/Animal Insurance (पशु विमा)",
    "Economic Condition of the House Owner Family/Insurance Details/If yes, what type of insurance have you or your family members taken? (यदि छ भने, तथा तपाँईको परिवारको कुनै सदस्यहरूले निम्न उल्लेख मध्ये कुन कुन विमा गर्नुभएको छ?)/Crop Insurance (बाली विमा)",
    "Economic Condition of the House Owner Family/Insurance Details/If yes, what type of insurance have you or your family members taken? (यदि छ भने, तथा तपाँईको परिवारको कुनै सदस्यहरूले निम्न उल्लेख मध्ये कुन कुन विमा गर्नुभएको छ?)/Health Insurance (स्वास्थ्य विमा)",
    "Economic Condition of the House Owner Family/Insurance Details/If yes, what type of insurance have you or your family members taken? (यदि छ भने, तथा तपाँईको परिवारको कुनै सदस्यहरूले निम्न उल्लेख मध्ये कुन कुन विमा गर्नुभएको छ?)/Other (अन्य)",
    "Economic Condition of the House Owner Family/Insurance Details/If other type of insurance, please specify (यदि अन्य विमा भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Economic Condition of the House Owner Family/Occupational and Livelihood/Do you or your family fall in the Occupational and livelihood groups mentioned below? ( तल उल्लेख  पेशागत र जीविकोपार्जन समूहमा तपाइँ र तपाइको परिवार पर्नुहुन्छ?)",
    "Economic Condition of the House Owner Family/Occupational and Livelihood/If other occupational and livelihood groups, please specify (यदि अन्य पेशागत र जीविकोपार्जन समुह भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Economic Condition of the House Owner Family/Communication/Do you have communication device at your house? (के तपाइँको घरमा संचार साधन उपलब्ध छ?)",
    "Economic Condition of the House Owner Family/Communication/If yes, what type of communication devices are at your house? (यदि छ भने, तल उल्लेख मध्ये कुन संचार माध्यम उपलब्ध छन्?)/Radio (रेडियो)",
    "Economic Condition of the House Owner Family/Communication/If yes, what type of communication devices are at your house? (यदि छ भने, तल उल्लेख मध्ये कुन संचार माध्यम उपलब्ध छन्?)/TV (टेलिभिजन)",
    "Economic Condition of the House Owner Family/Communication/If yes, what type of communication devices are at your house? (यदि छ भने, तल उल्लेख मध्ये कुन संचार माध्यम उपलब्ध छन्?)/Mobile Phone (मोबाइल फोन)",
    "Economic Condition of the House Owner Family/Communication/If yes, what type of communication devices are at your house? (यदि छ भने, तल उल्लेख मध्ये कुन संचार माध्यम उपलब्ध छन्?)/Telephone (टेलिफोन)",
    "Economic Condition of the House Owner Family/Communication/If yes, what type of communication devices are at your house? (यदि छ भने, तल उल्लेख मध्ये कुन संचार माध्यम उपलब्ध छन्?)/Internet (इन्टरनेट)",
    "Economic Condition of the House Owner Family/Communication/If yes, what type of communication devices are at your house? (यदि छ भने, तल उल्लेख मध्ये कुन संचार माध्यम उपलब्ध छन्?)/Computer (कम्प्यूटर)",
    "Economic Condition of the House Owner Family/Communication/If yes, what type of communication devices are at your house? (यदि छ भने, तल उल्लेख मध्ये कुन संचार माध्यम उपलब्ध छन्?)/Other (अन्य)",
    "Economic Condition of the House Owner Family/Communication/Specify other type of communication devices available at your house. (यदि अन्य संचार  साधन भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Economic Condition of the House Owner Family/Communication/If No, what is the medium of communication in the house? (यदि छैन भने,  संचारको अन्य माध्यमहरु के प्रयोग/उपलब्ध हुन्छ?)/Community Library (सामुदायिक पुस्तकालय)",
    "Economic Condition of the House Owner Family/Communication/If No, what is the medium of communication in the house? (यदि छैन भने,  संचारको अन्य माध्यमहरु के प्रयोग/उपलब्ध हुन्छ?)/Community Centre (सामुदायिक केन्द्र)",
    "Economic Condition of the House Owner Family/Communication/If No, what is the medium of communication in the house? (यदि छैन भने,  संचारको अन्य माध्यमहरु के प्रयोग/उपलब्ध हुन्छ?)/Other Medium of Communication (अन्य कुनै माध्यम)",
    "Economic Condition of the House Owner Family/Communication/If other medium, please specify here. (यदि अन्य माध्यम उपलब्ध भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Economic Condition of the House Owner Family/Communication/Do the women of the house have access to the communication devices? (घरका  महिला सदस्यको  संचार माध्यमको पहुँच छ?)",
    "Economic Condition of the House Owner Family/Communication/If no, what is the medium of communication used by the house? (यदि छैन भने,  संचारको अन्य माध्यमहरु के प्रयोग/उपलब्ध हुन्छ?)",
    "Access to Various Resources/Distance to nearest resources/Access to Drinking Water Facility/Access to Drinking Water Facility (पिउने पानी सुविधामा पहुँच)",
    "Access to Various Resources/Distance to nearest resources/Access to Drinking Water Facility/Please mention the distance of Drinking Water Facility from the house. (कृपया घरबाट खानेपानी सुविधाको दूरी उल्लेख गर्नुहोस्।)",
    "Access to Various Resources/Distance to nearest resources/Access to Drinking Water Facility/Please mention the unit of measurement of distance. (कृपया दूरी नाप्ने इकाइ उल्लेख गर्नुहोस्।)",
    "Access to Various Resources/Distance to nearest resources/Road/Is the nearest road accessible to people with disability? (नजिकैको बाटो फरक क्षमता भएकाहरुको पहुँचमा छ?)",
    "Access to Various Resources/Distance to nearest resources/Medical Center/Distance of medical centers from the house  (घरबाट नजिकैको  स्वास्थ्य संस्थाको दुरी)",
    "Access to Various Resources/Distance to nearest resources/Medical Center/Please mention the unit of measurement of distance. (कृपया दूरी नाप्ने इकाइ उल्लेख गर्नुहोस्।)",
    "Access to Various Resources/Distance to nearest resources/Medical Center/Is the medical center accessible to people with disability? (नजिकैको स्वास्थ्य संस्था  फरक क्षमता भएकाहरुको पहुँचमा छ?)",
    "Access to Various Resources/Distance to nearest resources/Market Place/Distance of nearest market from the house (घरबाट नजिकैको बजारको दुरी)",
    "Access to Various Resources/Distance to nearest resources/Market Place/Please mention the unit of measurement of distance. (कृपया दूरी नाप्ने इकाइ उल्लेख गर्नुहोस्।)",
    "Access to Various Resources/Distance to nearest resources/Sanitation/Access to the nearest toilet (नजिकैको शौचालय र घरको पहुँच)",
    "Access to Various Resources/Distance to nearest resources/Sanitation/Distance of the nearest toilet  (नजिकैको शौचालय र घरको दुरी)",
    "Access to Various Resources/Distance to nearest resources/Sanitation/Please mention the unit of measurement of distance. (कृपया दूरी नाप्ने इकाइ उल्लेख गर्नुहोस्।)",
    "Access to Various Resources/Distance to nearest resources/Sanitation/Is the toilet accessible to people with disability? (शौचालय शारिरिक तथा मानसिक अपांगता भएकाहरुको पहुँचमा छ?)",
    "Access to Various Resources/Distance to nearest resources/Sanitation/Access to safe and adequate sanitation especially for female to manage hygiene during menstruation (सुरक्षित र पर्याप्त सरसफाइमा पहुँच विशेष गरी महिलाहरूको लागि महिनावारीको समयमा स्वच्छता व्यवस्थापन गर्न)",
    "Access to Various Resources/Early Warning System/Do you have access to early warning information? (के तपाइँको घरमा पूर्व सुचना प्रणालीको जानकारी प्राप्त हुन्छ?)",
    "Access to Various Resources/Early Warning System/If early warning information is available, which medium is used to communicate the information? (यदि पूर्व सुचना उपलब्ध हुन्छ भने, कुन माध्यमद्वारा प्राप्त हुन्छ?)/Radio (रेडियो)",
    "Access to Various Resources/Early Warning System/If early warning information is available, which medium is used to communicate the information? (यदि पूर्व सुचना उपलब्ध हुन्छ भने, कुन माध्यमद्वारा प्राप्त हुन्छ?)/TV (टेलिभिजन)",
    "Access to Various Resources/Early Warning System/If early warning information is available, which medium is used to communicate the information? (यदि पूर्व सुचना उपलब्ध हुन्छ भने, कुन माध्यमद्वारा प्राप्त हुन्छ?)/Phone/SMS (फोन/ एस.एम.एस)",
    "Access to Various Resources/Early Warning System/If early warning information is available, which medium is used to communicate the information? (यदि पूर्व सुचना उपलब्ध हुन्छ भने, कुन माध्यमद्वारा प्राप्त हुन्छ?)/Internet (इन्टरनेट)",
    "Access to Various Resources/Early Warning System/If early warning information is available, which medium is used to communicate the information? (यदि पूर्व सुचना उपलब्ध हुन्छ भने, कुन माध्यमद्वारा प्राप्त हुन्छ?)/Miking (माइकिंग)",
    "Access to Various Resources/Early Warning System/If early warning information is available, which medium is used to communicate the information? (यदि पूर्व सुचना उपलब्ध हुन्छ भने, कुन माध्यमद्वारा प्राप्त हुन्छ?)/Siren ( साइरन)",
    "Access to Various Resources/Early Warning System/If early warning information is available, which medium is used to communicate the information? (यदि पूर्व सुचना उपलब्ध हुन्छ भने, कुन माध्यमद्वारा प्राप्त हुन्छ?)/Other (अन्य)",
    "Access to Various Resources/Early Warning System/If other medium, please specify the medium via which early warning information is provided. (यदि अन्य माध्यमबाट पुर्व सुचना प्राप्त हुन्छ भने, यहाँ उल्लेख गर्नुहोस)",
    "Access to Various Resources/Early Warning System/Do the women and children have access to early warning information? (के महिला र बाल-बालिकालाइ पूर्व सुचना प्रणालीको पहुँच छ?)",
    "Access to Various Resources/Early Warning System/Do you understand the early warning information disseminated? (प्राप्त भएको  पुर्वसुचना बुझ्नुहुन्छ?)",
    "Access to Various Resources/Safe Shelter/Do you have access to safe shelter? (के तपाइको सुरक्षित आवासमा पहुँच छ?)",
    "Access to Various Resources/Safe Shelter/If yes, how far is safe shelter from your house? (यदि छ भने, सुरक्षित आवास तपाइको घरबाट कति टाढा छ?)",
    "Access to Various Resources/Safe Shelter/Please select the unit of distance measurement. (कृपया दूरी मापनको इकाइ चयन गर्नुहोस्।)",
    "Access to Various Resources/Access to other resources/Access to clean drinking water during flood (बाढीको समयमा खानेपानीको सुविधा)",
    "Access to Various Resources/Access to other resources/Which type of natural resources do you have access to? (तल उल्लेख मध्ये कुन-कुन प्राकृतिक स्रोतहरुको पहुँच छ?)/Forest (वन)",
    "Access to Various Resources/Access to other resources/Which type of natural resources do you have access to? (तल उल्लेख मध्ये कुन-कुन प्राकृतिक स्रोतहरुको पहुँच छ?)/Water Resources (जलस्रोत)",
    "Access to Various Resources/Access to other resources/Which type of natural resources do you have access to? (तल उल्लेख मध्ये कुन-कुन प्राकृतिक स्रोतहरुको पहुँच छ?)/Other natural resources (अन्य प्राकृतिक स्रोत)",
    "Access to Various Resources/Access to other resources/Which type of natural resources do you have access to? (तल उल्लेख मध्ये कुन-कुन प्राकृतिक स्रोतहरुको पहुँच छ?)/Do not have access (कुनै पनि छैन)",
    "Access to Various Resources/Access to other resources/If other natural resources, please specify (यदि अन्य प्राकृतिक स्रोत भए, यहाँ उल्लेख गर्नुहोस)",
    "Details on the House/Structure Built and Permit/Age of the house (In years) (घर निर्माण भएको कति वर्ष भयो?)",
    "Details on the House/Structure Built and Permit/Number of storey of the house (घरको तल्ला)",
    "Details on the House/Structure Built and Permit/Is the building designed following building code? (के तपाइले घर बनाउदा भवन निर्माण संहिता पालना गरेर निर्माण गर्नुभएको हो?)",
    "Details on the House/Structure Built and Permit/Have you received a building permit from the municipality? ( नगरपालिकाबाट निर्माण स्वीकृति लिनुभएको छ?)",
    "Details on the House/Construction Materials/Type of foundation of the building (तल उल्लेख मध्ये तपाईको घरको जगको निर्माण सामाग्री के-के हुन्)",
    "Details on the House/Construction Materials/If other type of foundation materials, please specify. (यदि अन्य प्रकारको निर्माण सामग्री भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Details on the House/Construction Materials/Please mention the building type of your house (तपाइको घर तल उल्लेख मध्ये कुन किसिमको हो?)",
    "Details on the House/Construction Materials/If other type of building type, please specify. (यदि अन्य प्रकारको भवन भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Details on the House/Construction Materials/What materials are used for the construction of Wall of your house? (तपाइको घरको भित्ता के ले बनेको छ?)",
    "Details on the House/Construction Materials/If other wall type, please specify (यदि अन्य सामग्रीले बनेको भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Details on the House/Construction Materials/What materials are used for the construction of Roof of your house? (तपाइको घरको छाना केले निर्माण गरिएको छ?)",
    "Details on the House/Construction Materials/If other materials of roof, please specify. (यदि अन्य निर्माण सामग्रीले छाना बनेको भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Details on the House/Construction Materials/Is the roof easily accessible in case of any emergency? (के तपाइको घरको छतमा सजिलै जान र बस्न मिल्छ?)",
    "Details on the House/Current Condition/What is the current condition of your house? (तपाइको घरको अहिलेको अवस्था कस्तो छ?)",
    "Details on the House/Current Condition/How is the ground surface of the area in which your house has been built? (तपाईको घर निर्माण भएको जमिनको सतह कस्तो छ?)",
    "Details on the House/Current Condition/Does your house have the following features? (तपाइको घरमा तल उल्लेख मध्ये कुनै संरचना निर्माण गरिएको छ?)/Raised Plinth and above flood level (उठाएको प्लिन्थ-बाढीको सतह भन्दा माथि)",
    "Details on the House/Current Condition/Does your house have the following features? (तपाइको घरमा तल उल्लेख मध्ये कुनै संरचना निर्माण गरिएको छ?)/Strong wall (मजबुत पर्खाल)",
    "Details on the House/Current Condition/Does your house have the following features? (तपाइको घरमा तल उल्लेख मध्ये कुनै संरचना निर्माण गरिएको छ?)/Proper drainage (उचित ढल/जल निकासी)",
    "Details on the House/Current Condition/Does your house have the following features? (तपाइको घरमा तल उल्लेख मध्ये कुनै संरचना निर्माण गरिएको छ?)/None of the above (माथिको कुनै पनि होइन)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years, how many times have you experienced flooding events? (विगत ३० वर्षमा तपाइले कति पटक बाढीका घटनाहरुको अनुभव गर्नुभएको छ?)",
    "Hazard and Disaster/Historical Damage and Loss/In the past flooding events, what is the maximum depth of flood occurrence surrounding the household? विगतको बाढी घटनामा, घर वरिपरि बाढीको अधिकतम गहिराई कति थियो ?",
    "Hazard and Disaster/Historical Damage and Loss/Select the unit of flood depth measurement. (बाढीको गहिराई नाप्ने इकाइ चयन गर्नुहोस्।)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/Death of  household members (परिवारको सदस्यको मृत्यु भएको)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/Missing household members (परिवारको सदस्य हराएको)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/Injured household members (परिवारको सदस्य घाइते हुनुभएको)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/People displaced (विस्थापित)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/Damage to house (घरमा क्षति भएको)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/Land affected (जमिन क्षति भएको)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/Livestock affected (पशु क्षति भएको)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/Farmland affected (खेति जमिनमा क्षति)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/Damage to stored food stock (भण्डारण गरिएको खाद्यान्न क्षति)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/Non-Structural Damage (गैर-संरचनात्मक क्षति)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/Loss of other livelihood options ( such as loss of job, business, other than agriculture)",
    "Hazard and Disaster/Historical Damage and Loss/In the past 30 years what damages were caused by the flooding events occurred ? (विगत ३० वर्षमा अनुभव गर्नुभएको बाढीका घटनाहरुमा केहि क्षति भएको थियो?)/No any damage (कुनै पनि क्षति नभएको)",
    "Hazard and Disaster/Historical Damage and Loss/Number of people death (मृत्यु हुनेको संख्या)",
    "Hazard and Disaster/Historical Damage and Loss/Number of missing family members (हराएका परिवारको सदस्यको संख्या)",
    "Hazard and Disaster/Historical Damage and Loss/Number of injured family members (घाइतेको संख्या)",
    "Hazard and Disaster/Historical Damage and Loss/Number of people displaced (विस्थापित संख्या)",
    "Hazard and Disaster/Historical Damage and Loss/Total area of farmland affected (कुल खेति जमिन क्षति)",
    "Hazard and Disaster/Historical Damage and Loss/Unit of measurement of affected farmland area (प्रभावित खेति जमिन क्षेत्रको मापनको इकाइ)",
    "Hazard and Disaster/Historical Damage and Loss/Estimated agricultural loss (कुल कृषि क्षति)",
    "Hazard and Disaster/Historical Damage and Loss/Type of damage to the house (घरको क्षतिको प्रकार)",
    "Hazard and Disaster/Historical Damage and Loss/Total livestock loss (कुल पशु क्षतिको संख्या)",
    "Hazard and Disaster/Historical Damage and Loss/Estimated livestock loss NPR (कुल पशु क्षति)",
    "Hazard and Disaster/Historical Damage and Loss/Total loss of stored food KG (भण्डारण गरिएको खाद्यान्न क्षति)",
    "Hazard and Disaster/Historical Damage and Loss/Total Estimated loss NPR (कुल अनुमानित क्षति)",
    "Hazard and Disaster/Historical Damage and Loss/If loss of other livelihood options, please specify. अन्य जीविकोपार्जनका विकल्पहरू गुमाएमा, कृपया यहाँ उल्लेख गर्नुहोस्।",
    "Hazard and Disaster/Knowledge and Training in Disaster/Have any family members received training on disaster? (के तपाइँ वा तपाईको परिवारको सदस्यले विपद सम्बन्धी तालिम लिनुभएको छ?)",
    "Hazard and Disaster/Knowledge and Training in Disaster/If yes, type of training received (यदि तालिम लिनुभएको छ भने, तल उल्लेख मध्ये कुन-कुन तालिम लिनुभएको छ?)/First Aid (प्राथमिक उपचार)",
    "Hazard and Disaster/Knowledge and Training in Disaster/If yes, type of training received (यदि तालिम लिनुभएको छ भने, तल उल्लेख मध्ये कुन-कुन तालिम लिनुभएको छ?)/Search and rescue (खोज तथा उद्दार)",
    "Hazard and Disaster/Knowledge and Training in Disaster/If yes, type of training received (यदि तालिम लिनुभएको छ भने, तल उल्लेख मध्ये कुन-कुन तालिम लिनुभएको छ?)/Simulation and drill exercise (सिमुलेशन र ड्रिल)",
    "Hazard and Disaster/Knowledge and Training in Disaster/If yes, type of training received (यदि तालिम लिनुभएको छ भने, तल उल्लेख मध्ये कुन-कुन तालिम लिनुभएको छ?)/Other Disaster related training (विपद सम्बन्धी अन्य तालिम)",
    "Hazard and Disaster/Knowledge and Training in Disaster/If other disaster related trainings received, please specify what type of trainings. (यदि विपद सम्बन्धी अन्य तालिम भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Hazard and Disaster/Aftermath of Past Disaster/Access to social assistance in the aftermath of past disaster (विगतको प्रकोप पछि सामाजिक सहायता प्राप्त भएको थियो?)",
    "Community Groups/Are you or any of your family are a member of any of the following community groups? (के तपाइँ वा परिवारको सदस्य तल उल्लेख मध्ये कुनै समूहको सदस्य हुनुहुन्छ?)/DRRM committee of ward/municipality (पालिका वा वडाको विपद सम्बन्धी समितिमा)",
    "Community Groups/Are you or any of your family are a member of any of the following community groups? (के तपाइँ वा परिवारको सदस्य तल उल्लेख मध्ये कुनै समूहको सदस्य हुनुहुन्छ?)/Women group (महिला समुह)",
    "Community Groups/Are you or any of your family are a member of any of the following community groups? (के तपाइँ वा परिवारको सदस्य तल उल्लेख मध्ये कुनै समूहको सदस्य हुनुहुन्छ?)/Youth group (युवा समुह)",
    "Community Groups/Are you or any of your family are a member of any of the following community groups? (के तपाइँ वा परिवारको सदस्य तल उल्लेख मध्ये कुनै समूहको सदस्य हुनुहुन्छ?)/Child group (बाल समुह)",
    "Community Groups/Are you or any of your family are a member of any of the following community groups? (के तपाइँ वा परिवारको सदस्य तल उल्लेख मध्ये कुनै समूहको सदस्य हुनुहुन्छ?)/Single women's group (एकल महिला समुह)",
    "Community Groups/Are you or any of your family are a member of any of the following community groups? (के तपाइँ वा परिवारको सदस्य तल उल्लेख मध्ये कुनै समूहको सदस्य हुनुहुन्छ?)/Scout/Red cross (स्काउट/ रेड क्रस)",
    "Community Groups/Are you or any of your family are a member of any of the following community groups? (के तपाइँ वा परिवारको सदस्य तल उल्लेख मध्ये कुनै समूहको सदस्य हुनुहुन्छ?)/Other (अन्य)",
    "Community Groups/Are you or any of your family are a member of any of the following community groups? (के तपाइँ वा परिवारको सदस्य तल उल्लेख मध्ये कुनै समूहको सदस्य हुनुहुन्छ?)/No (कुनैमा पनि छैन)",
    "Community Groups/If other, please specify. (यदि अन्य समुह भएमा, यहाँ उल्लेख गर्नुहोस)",
    "Community Groups/Women's participation in community/ ward/ municipal meeting and or decision making process (सामुदायिक/वडा/नगरपालिका  बैठक र निर्णय प्रक्रियामा घरको महिलाहरूको सहभागिता)",
    "Citizenship Number of House Owner (नागरिकता नं)",
    "Phone number (फोन नं)",
    "Please take the picture of the house (सर्वेक्षण गरेको घरको फोटो खिच्नुहोस)",
    "Please take the picture of the house (सर्वेक्षण गरेको घरको फोटो खिच्नुहोस)_URL",
    "unique_identity",
    "Your household unique ID is ",
    "__version__",
    "_id",
    "_uuid",
    "_submission_time",
    "_validation_status",
    "_notes",
    "_status",
    "_submitted_by",
    "_tags",
    "_index",
    "Unnamed: 341",
    "Unnamed: 342",
    "Unnamed: 343",
    "Unnamed: 344",
    "परिवारको जग्गा in KATHA",
    "महिला सदस्यको नाममा भएको जग्गा in KATHA",
    "घरबाट खानेपानी सुविधाको दूरी in METER",
    "घरबाट स्वास्थ्य संस्थाको दुरी in METER",
    "(घरबाट बजारको दुरी in METER",
    "(नजिकैको शौचालय र घरको दुरी in METER",
    "(Distance to safe Shelter in METER)"
  ]